# ruff: noqa
# Mirrored from SLNG. Not first-party source: the platform gated this
# module and owns it. Edit it in the SLNG dashboard, not here.
"""Look up an order.

Stands in for a real system. A tool on SLNG has no network access at all, so a
handler that needs to reach a service has to be a `webhook:` tool instead. This
one answers from a table, which is what makes the example deployable with
nothing provisioned.
"""

ORDERS = {
    "A-1001": ("shipped", "2026-09-02"),
    "A-1002": ("packing", "2026-09-05"),
    "A-1003": ("delivered", "2026-08-21"),
}


def check_order(order_number: str) -> dict:
    status, delivers_on = ORDERS.get(order_number.strip().upper(), ("unknown", ""))
    return {"status": status, "delivers_on": delivers_on}


# Generated by unmute. SLNG derives this tool's parameter and result
# schemas by introspecting Input and Output, and calls handler().
# Everything above this line is your own handler file, unchanged.
from pydantic import BaseModel


class Input(BaseModel):
    order_number: str


class Output(BaseModel):
    delivers_on: str | None = None
    status: str | None = None


def handler(input: Input) -> Output:
    result = check_order(order_number=input.order_number)
    return Output(**result)
