//go:build sweep

// L5 example sweep: the acceptance harness for specs/011-complexity-cleanup.
//
// Goldens pin generated bytes, but most of the code this feature touches
// produces no generated bytes — it lives in the command layer, where the only
// proof is running. So this compiles every example, compares the result against
// a baseline byte for byte, and then drives each browser-runnable example
// through `unmute dev` until the agent's voice actually arrives.
//
// Opt-in, exactly like L4: a build tag, out of the default suite and the PR
// gate, blocking (not failing) when its tooling is absent.
//
//	go test -tags sweep ./internal/cli/... -run TestExampleSweep -timeout 90m
//
// Contract: specs/011-complexity-cleanup/contracts/sweep-report.md.
package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/slng-ai/unmute/internal/ir"
)

// Environment the harness reads. All optional except the baseline, which the
// byte comparison cannot be done without.
const (
	sweepBaselineEnv   = "UNMUTE_SWEEP_BASELINE"   // baseline tree from T004
	sweepReportDirEnv  = "UNMUTE_SWEEP_REPORT_DIR" // where the JSON report lands
	sweepStoryEnv      = "UNMUTE_SWEEP_STORY"      // "P1".."P5", or "baseline"
	sweepPlaywrightEnv = "UNMUTE_SWEEP_PLAYWRIGHT" // playwright module path for the probe
	sweepOnlyEnv       = "UNMUTE_SWEEP_ONLY"       // comma-separated example names, for triage
)

// One port pair for the whole sweep. Sessions run serially, so there is nothing
// to allocate and no way for two runs to interleave their logs (research.md R6).
const (
	sweepUIPort  = "8765"
	sweepBotPort = "7860"
)

const (
	sweepReadyTimeout = 12 * time.Minute // first run builds images from scratch
	sweepProbeTimeout = 90 * time.Second // page load, connect, greeting
	sweepStopGrace    = 60 * time.Second
)

// preservedPatterns files are restored into a build directory on purpose
// (compile.go), so comparing them compares the sweep against itself.
var sweepIgnored = []string{".env", "livekit.toml", "livekit-sip.toml"}

// sweepVars seeds input variables a greeting interpolates. salon-support's
// greeting is "Hi {{customer_name}}" from source: call_start, so without these
// it renders malformed and the session would fail for a reason that has nothing
// to do with the code under test. multi-task declares the same two names but
// neither is call_start and its greeting interpolates nothing, so it needs none
// (research.md R5, closed).
var sweepVars = map[string][]string{
	"salon-support": {"customer_name=Robin", "customer_id=cus_0042"},
}

type sweepSession struct {
	Example string  `json:"example"`
	Target  string  `json:"target"`
	Outcome string  `json:"outcome"` // passed | failed | blocked
	Seconds float64 `json:"seconds"`
}

type sweepReport struct {
	Story          string         `json:"story"`
	Commit         string         `json:"commit"`
	RuffVersion    string         `json:"ruffVersion"`
	ByteDiff       string         `json:"byteDiff"` // clean | dirty | unknown
	Verdict        string         `json:"verdict"`  // derived, never assigned
	Sessions       []sweepSession `json:"sessions"`
	MissingSecrets []string       `json:"missingSecrets"` // names only, never values
}

// verdict is derived so a blocked sweep can never read as a pass. Anything
// short of every session passed and a clean diff is "incomplete" at best.
func (r sweepReport) verdict() string {
	if r.ByteDiff != "clean" || len(r.Sessions) == 0 {
		return "incomplete"
	}
	for _, s := range r.Sessions {
		if s.Outcome == "failed" {
			return "red"
		}
		if s.Outcome != "passed" {
			return "incomplete"
		}
	}
	return "green"
}

type sweepExample struct {
	Name     string
	Dir      string
	Targets  []string // code targets, sorted
	Runnable bool     // no telephony channel: FR-031 makes carrier routes compile-only
}

// TestExampleSweep is the whole layer: one root test, one subtest per example
// and target, so `go test -v` is the report and FR-034 needs no extra machinery.
func TestExampleSweep(t *testing.T) {
	root := repoRoot(t)
	t.Chdir(root)

	examples := discoverExamples(t, root)
	report := sweepReport{
		Story:       cmpOrEnv(sweepStoryEnv, "unnamed"),
		Commit:      capture(t, "git", "rev-parse", "--short", "HEAD"),
		RuffVersion: capture(t, "ruff", "--version"),
		ByteDiff:    "unknown",
	}

	t.Run("preflight", func(t *testing.T) {
		report.MissingSecrets = sweepPreflight(t, root, examples)
	})

	binary := buildUnmute(t, root)

	t.Run("compile", func(t *testing.T) {
		compileAll(t, binary, examples)
		report.ByteDiff = compareToBaseline(t, root, examples)
	})

	for _, ex := range examples {
		if !ex.Runnable {
			continue
		}
		t.Run(ex.Name, func(t *testing.T) {
			for _, target := range ex.Targets {
				t.Run(target, func(t *testing.T) {
					started := time.Now()
					outcome := runSession(t, binary, ex, target)
					report.Sessions = append(report.Sessions, sweepSession{
						Example: ex.Name, Target: target, Outcome: outcome,
						Seconds: float64(int(time.Since(started).Seconds()*10)) / 10,
					})
				})
			}
		})
	}

	report.Verdict = report.verdict()
	writeSweepReport(t, report)
}

// --- discovery ---------------------------------------------------------

// repoRoot walks up from the package directory. The harness must run from the
// repository root: `unmute dev` reads $CWD/.env for credentials, which is what
// makes FR-036 free — no secret is ever copied anywhere (research.md R4).
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolve repository root: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "go.mod")); err != nil {
		t.Fatalf("not the repository root (no go.mod at %s): %v", dir, err)
	}
	return dir
}

// discoverExamples derives the runnable set rather than hard-coding it, so an
// example added later is classified without editing the harness. An example is
// compile-only when it declares a telephony channel: those routes need a
// carrier, and FR-031 keeps them out of the browser sweep.
func discoverExamples(t *testing.T, root string) []sweepExample {
	t.Helper()
	entries, err := os.ReadDir(filepath.Join(root, "examples"))
	if err != nil {
		t.Fatalf("read examples: %v", err)
	}
	only := map[string]bool{}
	for _, name := range strings.Split(os.Getenv(sweepOnlyEnv), ",") {
		if name = strings.TrimSpace(name); name != "" {
			only[name] = true
		}
	}

	var out []sweepExample
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		dir := filepath.Join("examples", entry.Name())
		if _, err := os.Stat(filepath.Join(root, dir, "agent.yaml")); err != nil {
			continue
		}
		if len(only) > 0 && !only[entry.Name()] {
			continue
		}
		agent, targets, err := loadPackage(dir, nil)
		if err != nil {
			t.Fatalf("load %s: %v", dir, err)
		}
		ex := sweepExample{Name: entry.Name(), Dir: dir, Runnable: true}
		for _, channel := range agent.Channels {
			if channel.Kind == ir.ChannelTelephony {
				ex.Runnable = false
			}
		}
		for _, target := range targets {
			if target.Provider == ir.ProviderPipecat || target.Provider == ir.ProviderLiveKit {
				ex.Targets = append(ex.Targets, target.Name)
			}
		}
		slices.Sort(ex.Targets)
		out = append(out, ex)
	}
	return out
}

// --- preflight ---------------------------------------------------------

// sweepPreflight checks everything before the first container builds. Missing
// tooling BLOCKS: it says nothing about the code under test, which is the same
// rule L4 applies to uv. A missing secret FAILS: the sweep cannot deliver the
// coverage it claims, and FR-035 forbids reporting that as anything else.
func sweepPreflight(t *testing.T, root string, examples []sweepExample) []string {
	t.Helper()
	docker, err := exec.LookPath("docker")
	if err != nil {
		t.Skip("blocked: docker is not installed")
	}
	if out, err := exec.Command(docker, "info").CombinedOutput(); err != nil {
		t.Skipf("blocked: docker daemon unavailable: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	probe := exec.Command("node", "-e", "require(process.env.UNMUTE_SWEEP_PLAYWRIGHT||'playwright')")
	probe.Env = append(os.Environ(), sweepPlaywrightEnv+"="+os.Getenv(sweepPlaywrightEnv))
	if out, err := probe.CombinedOutput(); err != nil {
		t.Skipf("blocked: playwright is not resolvable (set %s to its module path): %v\n%s",
			sweepPlaywrightEnv, err, strings.TrimSpace(string(out)))
	}
	if busy := busyPorts(); len(busy) > 0 {
		// Sessions run serially on fixed ports, so anything already holding one
		// stops the sweep dead. A stale `unmute dev` container from an earlier
		// run is the usual cause, and it says nothing about the code — block.
		t.Skipf("blocked: ports already in use: %s\n"+
			"        a previous `unmute dev` container is probably still up; `docker ps` then `docker rm -f` them",
			strings.Join(busy, ", "))
	}
	if os.Getenv(sweepBaselineEnv) == "" {
		t.Fatalf("%s is unset: with no baseline tree there is nothing to compare against (FR-001)", sweepBaselineEnv)
	}

	present, err := parseDotenv(filepath.Join(root, ".env"))
	if err != nil {
		t.Fatalf("read root .env: %v", err)
	}
	var missing []string
	for _, name := range declaredSecrets(t, root, examples) {
		if present[name] == "" && os.Getenv(name) == "" {
			missing = append(missing, name)
		}
	}
	if len(missing) > 0 {
		// Names only. No value from .env may reach a log, a report, or a
		// failure message (FR-036, SC-011).
		t.Fatalf("missing required secrets (names only): %s", strings.Join(missing, ", "))
	}
	return []string{}
}

// busyPorts names the fixed ports a session needs that something else already
// holds: the dev UI, the published bot, and the two TCP ports the dev
// livekit-server publishes.
func busyPorts() []string {
	var busy []string
	for _, port := range []string{sweepUIPort, sweepBotPort, "7880", "7881"} {
		listener, err := net.Listen("tcp", net.JoinHostPort("127.0.0.1", port))
		if err != nil {
			busy = append(busy, port)
			continue
		}
		_ = listener.Close()
	}
	return busy
}

// declaredSecrets reads the compile report each example already emits, so the
// required set is derived from the compiler rather than restated here. Only the
// runnable examples count: the carrier ones never start a container.
func declaredSecrets(t *testing.T, root string, examples []sweepExample) []string {
	t.Helper()
	var names []string
	for _, ex := range examples {
		if !ex.Runnable {
			continue
		}
		for _, target := range ex.Targets {
			path := filepath.Join(root, ex.Dir, "build", target, "compile-report.json")
			raw, err := os.ReadFile(path)
			if err != nil {
				continue // not compiled yet; the compile subtest covers it
			}
			var report struct {
				Secrets []struct {
					Name string `json:"name"`
				} `json:"secrets"`
			}
			if err := json.Unmarshal(raw, &report); err != nil {
				t.Fatalf("parse %s: %v", path, err)
			}
			for _, secret := range report.Secrets {
				names = append(names, secret.Name)
			}
		}
	}
	slices.Sort(names)
	return slices.Compact(names)
}

// --- compile and byte comparison ---------------------------------------

func buildUnmute(t *testing.T, root string) string {
	t.Helper()
	binary := filepath.Join(t.TempDir(), "unmute")
	build := exec.Command("go", "build", "-o", binary, ".")
	build.Dir = root
	build.Env = append(os.Environ(), "CGO_ENABLED=0")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build unmute under test: %v\n%s", err, out)
	}
	return binary
}

// compileAll compiles every example, carrier ones included. That is the whole
// of FR-031's compile-only coverage: the telephony routes are proved by their
// bytes, not by a call.
func compileAll(t *testing.T, binary string, examples []sweepExample) {
	t.Helper()
	for _, ex := range examples {
		cmd := exec.Command(binary, "compile", ex.Dir)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("compile %s: %v\n%s", ex.Name, err, out)
		}
	}
}

// compareToBaseline is FR-001 made checkable. A single differing byte is a
// failure, and the response is to fix the code — never to refresh the baseline,
// which is the claim being tested.
func compareToBaseline(t *testing.T, root string, examples []sweepExample) string {
	t.Helper()
	baseline := os.Getenv(sweepBaselineEnv)
	var differences []string
	for _, ex := range examples {
		for _, target := range ex.Targets {
			was := filepath.Join(baseline, ex.Name, target)
			now := filepath.Join(root, ex.Dir, "build", target)
			differences = append(differences, diffTrees(t, was, now, ex.Name+"/"+target)...)
		}
	}
	if len(differences) == 0 {
		return "clean"
	}
	t.Errorf("generated output changed in %d place(s); FR-001 says it must not:\n  %s",
		len(differences), strings.Join(differences, "\n  "))
	return "dirty"
}

func diffTrees(t *testing.T, was, now, label string) []string {
	t.Helper()
	left, right := treeFiles(t, was), treeFiles(t, now)
	var out []string
	for name, sum := range left {
		other, ok := right[name]
		switch {
		case !ok:
			out = append(out, label+"/"+name+": missing now")
		case other != sum:
			out = append(out, label+"/"+name+": bytes differ")
		}
	}
	for name := range right {
		if _, ok := left[name]; !ok {
			out = append(out, label+"/"+name+": new file")
		}
	}
	slices.Sort(out)
	return out
}

func treeFiles(t *testing.T, dir string) map[string]string {
	t.Helper()
	files := map[string]string{}
	err := filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		if slices.Contains(sweepIgnored, filepath.Base(rel)) {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		files[rel] = string(raw)
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		t.Fatalf("walk %s: %v", dir, err)
	}
	return files
}

// --- one live session --------------------------------------------------

// runSession is the part goldens cannot reach: start the real command, let it
// build and run the real container, and drive the real page until the agent's
// voice arrives. Serial, one port, containers down on every exit path.
func runSession(t *testing.T, binary string, ex sweepExample, target string) string {
	t.Helper()
	args := []string{"dev", ex.Dir, "--target", target, "--no-open",
		"--port", sweepUIPort, "--bot-port", sweepBotPort}
	for _, v := range sweepVars[ex.Name] {
		args = append(args, "--var", v)
	}

	logPath := filepath.Join(ex.Dir, "build", target, "dev.log")
	child := exec.Command(binary, args...)
	ownProcessGroup(child)
	output := &lockedBuffer{}
	child.Stdout, child.Stderr = output, output
	if err := child.Start(); err != nil {
		t.Fatalf("%s/%s: start dev: %v", ex.Name, target, err)
	}

	// Closed after the send, so every later receive returns at once. Two places
	// wait on this — readiness and teardown — and a plain send would let the
	// first one consume the only value and hang the second forever.
	done := make(chan error, 1)
	go func() { done <- child.Wait(); close(done) }()
	t.Cleanup(func() { stopSession(child, done) })

	if reason := waitForDevServer(done); reason != "" {
		t.Errorf("%s/%s: %s\n"+
			"        stage:    dev-start\n%s", ex.Name, target, reason, failureContext(output, logPath))
		return "failed"
	}

	result, err := runProbe(t)
	if err != nil {
		t.Errorf("%s/%s: %v\n"+
			"        stage:    audio-wait\n"+
			"        probe:    %s\n%s",
			ex.Name, target, err, result, failureContext(output, logPath))
		return "failed"
	}
	t.Logf("%s/%s: %s", ex.Name, target, result)
	return "passed"
}

// waitForDevServer polls the bootstrap endpoint the page itself calls and
// returns "" once it answers. It gives up as soon as the command exits, so a
// container that dies on startup is reported in seconds. The two ways of not
// being ready get different words: "the command exited" and "the deadline
// passed" send a reader to entirely different places.
func waitForDevServer(done <-chan error) string {
	deadline := time.Now().Add(sweepReadyTimeout)
	client := &http.Client{Timeout: 3 * time.Second}
	url := "http://127.0.0.1:" + sweepUIPort + "/api/session"
	for time.Now().Before(deadline) {
		select {
		case <-done:
			return "`unmute dev` exited before the dev server answered"
		default:
		}
		if resp, err := client.Get(url); err == nil {
			_ = resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				return ""
			}
		}
		time.Sleep(time.Second)
	}
	return fmt.Sprintf("dev server never came up within %s", sweepReadyTimeout)
}

func runProbe(t *testing.T) (string, error) {
	t.Helper()
	script := filepath.Join("internal", "testdata", "sweep", "greeting-probe.js")
	url := "http://localhost:" + sweepUIPort + "/"
	probe := exec.Command("node", script, url, fmt.Sprint(int(sweepProbeTimeout.Seconds())))
	probe.Env = os.Environ()
	out, err := probe.CombinedOutput()
	line := strings.TrimSpace(string(out))
	if err != nil {
		return line, fmt.Errorf("no inbound audio within %s", sweepProbeTimeout)
	}
	return line, nil
}

// stopSession asks the whole process group to exit so `unmute dev`'s own
// deferred teardown runs and takes the containers with it, then hard-kills if
// it does not. Containers must never outlive a session; the next one reuses
// the same ports.
func stopSession(child *exec.Cmd, done <-chan error) {
	if child.Process == nil {
		return
	}
	signalGroup(child, syscall.SIGINT)
	select {
	case <-done:
	case <-time.After(sweepStopGrace):
		signalGroup(child, syscall.SIGKILL)
		<-done
	}
}

// --- reporting ---------------------------------------------------------

// failureContext is what turns a red line into a fixed bug. A bare "session did
// not start" costs the reader the whole debug, so every failure carries the
// command's own output and the tail of the container log.
func failureContext(output *lockedBuffer, logPath string) string {
	context := "        command: " + indent(tail(output.String(), 20))
	if raw, err := os.ReadFile(logPath); err == nil {
		context += "\n        logs:    " + indent(tail(string(raw), 40))
	}
	return context
}

func tail(s string, n int) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	if len(lines) > n {
		lines = lines[len(lines)-n:]
	}
	return strings.Join(lines, "\n")
}

func indent(s string) string { return strings.ReplaceAll(s, "\n", "\n                 ") }

// lockedBuffer collects the command's output. The child writes stdout and
// stderr to the same sink from two goroutines, so the mutex is not optional.
type lockedBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *lockedBuffer) Write(p []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(p)
}

func (b *lockedBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}

// writeSweepReport writes to the scratch directory, never into the repository.
// No field may carry a secret value; missingSecrets holds names (FR-036).
func writeSweepReport(t *testing.T, report sweepReport) {
	t.Helper()
	dir := os.Getenv(sweepReportDirEnv)
	if dir == "" {
		dir = t.TempDir()
	}
	name := fmt.Sprintf("sweep-%s-%s.json", report.Story, report.Commit)
	raw, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("encode report: %v", err)
	}
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, append(raw, '\n'), 0o644); err != nil {
		t.Fatalf("write report: %v", err)
	}
	t.Logf("verdict %s — %s", report.Verdict, path)
}

// --- small helpers -----------------------------------------------------

func cmpOrEnv(name, fallback string) string {
	if v := os.Getenv(name); v != "" {
		return v
	}
	return fallback
}

// capture records a tool version or a sha for the report. A missing tool is not
// a failure here — the preflight decides what is required.
func capture(t *testing.T, name string, args ...string) string {
	t.Helper()
	out, err := exec.Command(name, args...).Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}
