# ruff: noqa
# Mirrored from SLNG. Not first-party source: the platform gated this
# module and owns it. Edit it in the SLNG dashboard, not here.
"""Look up an order.

Answers from a table, so the fixture needs nothing provisioned.
"""

ORDERS = {
    "A-1001": ("shipped", "2026-09-02"),
    "A-1002": ("packing", "2026-09-05"),
}


def check_order(order_id: str) -> dict:
    status, delivers_on = ORDERS.get(order_id.strip().upper(), ("unknown", ""))
    return {"status": status, "delivers_on": delivers_on}


# Generated by unmute. SLNG derives this tool's parameter and result
# schemas by introspecting Input and Output, and calls handler().
# Everything above this line is your own handler file, unchanged.
from pydantic import BaseModel


class Input(BaseModel):
    order_id: str


class Output(BaseModel):
    delivers_on: str | None = None
    status: str | None = None


def handler(input: Input) -> Output:
    result = check_order(order_id=input.order_id)
    return Output(**result)
