package generate

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/slng-ai/unmute/internal/ir"
)

// The pre-fetch block, and the one place its words are written.
//
// Facts knowable before the greeting are resolved here, once per call, so the
// model is never asked to discover them. Following guard.go: one file owns the
// emitted text, both drivers render what it produces, and the two targets agree
// by construction rather than by a test that has to notice they stopped
// agreeing. The test still exists, because construction can be undone.

// PrefetchBudget bounds the whole block, in seconds.
//
// Not a knob, and not per entry. Nobody has a second number to write, and a
// lookup slower than this is broken rather than slow: two seconds is already
// longer than a caller will wait for a greeting. It bounds the block rather than
// each entry so the ceiling is the thing the author can reason about, which is
// how long the greeting can be delayed in the worst case.
const PrefetchBudget = 2.0

// PrefetchRouterValueMax bounds one pre-fetched value where it is sent to the
// SLNG Context Router, in characters.
//
// This cannot be a compile-time refusal: the length is only known while the call
// runs. What it must not be is unbounded. A value that quietly outgrows what the
// router accepts takes the prompt caching with it, and the whole reason a
// pre-fetched value travels beside the prompt rather than inside it is to leave
// that caching alone. Shortening one is logged with its name, because a silent
// truncation of a customer's name is a worse outcome than a long log line.
const PrefetchRouterValueMax = 512

// PrefetchRequest is how one entry's tool call is made. The driver fills it from
// the same helpers its mid-call tool path uses (urlExpr, requestBody,
// callKwargs, loweredAuth) with its own state expression, so a pre-fetched
// webhook and a mid-call webhook cannot drift in the parts that actually drift:
// URL assembly, auth headers and the injected values.
//
// ponytail: the emitted request lines themselves live below rather than in a
// template partial shared with the tool method. Both drivers already spell a
// webhook the same way (httpx.AsyncClient().post) and a local handler the same
// way (tools.<name>.<name>), so there are six lines here and they are asserted.
// Factor them into a shared partial when a third execution kind becomes
// pre-fetchable and the shapes stop being identical.
type PrefetchRequest struct {
	Local      bool
	Name       string // the tool name, which is also its module and function name
	URLExpr    string
	AuthExpr   string
	BodyExpr   string
	CallKwargs string
}

// PrefetchBlock is what a driver renders: the Python, plus what the template
// needs to know without re-deriving it.
type PrefetchBlock struct {
	Source      string
	Timezone    string
	NeedsClock  bool
	NeedsAsync  bool
	NeedsLocal  bool
	NeedsSeed   bool
	Unconfirmed bool
}

// LocalCallFactsEnv carries the facts `unmute dev --source` seeds, as a JSON
// object, so the browser loop exercises the same code a phone call does.
//
// A second name beside UNMUTE_CALL_START, not a widening of it, and that is the
// whole point: the dispatch payload and the carrier's own facts are different
// things arriving through different doors, and seeding a variable directly would
// skip the pre-fetch, mark nothing as awaiting confirmation, and let a local run
// pass a path a real call fails.
const LocalCallFactsEnv = "UNMUTE_CALL_FACTS"

// Prefetch returns the block for a package, and whether the package needs one.
//
// A package that declares no `prefetch:` gets no block and no behaviour change:
// its emitted output is byte-for-byte what it was before this existed. That is
// why this returns a flag rather than always emitting a helper nothing calls,
// exactly as PrerequisiteGuard does.
func Prefetch(agent *ir.Agent, stateExpr string, request func(entry ir.Prefetch) PrefetchRequest) (PrefetchBlock, bool) {
	if len(agent.Prefetch) == 0 {
		return PrefetchBlock{}, false
	}
	block := PrefetchBlock{Timezone: agent.Timezone}
	var b strings.Builder
	b.WriteString(`# Pre-fetch, generated by internal/generate/prefetch.go.
#
# Facts that are knowable before the greeting are resolved here, once per call,
# so the model is never asked to discover them. An entry whose inputs are empty
# is skipped and the values keep their declared defaults, which is what makes a
# package that pre-fetches a carrier fact still work on a route that supplies
# none. Nothing here can fail a call.
_PREFETCH_BUDGET_S = ` + strconv.FormatFloat(PrefetchBudget, 'f', 1, 64) + `
_PREFETCH_VALUE_MAX = ` + strconv.Itoa(PrefetchRouterValueMax) + `
`)
	for _, entry := range agent.Prefetch {
		if entry.Clock != "" {
			block.NeedsClock = true
		}
		if entry.Tool != "" {
			block.NeedsAsync = true
			if agent.Tools[entry.Tool].Execution == ir.ToolLocal {
				block.NeedsLocal = true
			}
		}
		if entry.Source != "" {
			block.NeedsSeed = true
		}
		if prefetchConfirms(agent, entry) {
			block.Unconfirmed = true
		}
	}
	if block.NeedsClock {
		b.WriteString("_PREFETCH_TZ = ZoneInfo(" + pyQuote(agent.Timezone) + ")\n")
	}
	if block.NeedsSeed {
		b.WriteString(`

def _prefetch_call_facts(call_context):
    """The call's own facts, with the local seed filling only what the carrier did not.

    ` + LocalCallFactsEnv + ` is what ` + "`unmute dev --source name=value`" + ` sets. The
    carrier wins wherever it supplied a value: a seed stands in for a fact it
    could not supply, and never overrides one it did, so a stale value in a .env
    cannot quietly reshape a real call.

    Merging here rather than at each call site is deliberate. This driver starts a
    session from four different places, and a merge written four times is a merge
    that disagrees with itself in one of them.
    """
    facts = dict(call_context or {})
    seeded = os.environ.get(` + pyQuote(LocalCallFactsEnv) + `)
    if not seeded:
        return facts
    try:
        values = json.loads(seeded)
        for name in values:
            if not facts.get(name):
                facts[name] = values[name]
    except (ValueError, TypeError):
        logger.warning(
            ` + pyQuote(LocalCallFactsEnv+" is not a JSON object of call facts; ignoring it") + `
        )
    return facts
`)
	}
	b.WriteString(`

def _prefetch_bounded(name, value):
    """Bound one pre-fetched value, and say so when it is shortened.

    The length is only knowable here, at run time, so this cannot be a
    compile-time refusal. Silence is the one thing it must not be.
    """
    text = "" if value is None else str(value)
    if len(text) <= _PREFETCH_VALUE_MAX:
        return text
    logger.warning(
        f"prefetch: {name} was {len(text)} characters and is cut to "
        f"{_PREFETCH_VALUE_MAX}; a value this long stops the prompt being cached"
    )
    return text[:_PREFETCH_VALUE_MAX]


async def _prefetch(state, call_context) -> None:
`)
	if block.NeedsSeed {
		b.WriteString("    call_context = _prefetch_call_facts(call_context)\n")
	}
	if block.Unconfirmed {
		b.WriteString(`    # Every value awaiting the caller's agreement. The prerequisite guard reads
    # this set, so an unconfirmed value satisfies no step, and each generated
    # assign write discards its own name as the caller settles it.
    state._unconfirmed = set()
`)
	}
	b.WriteString(`    # Entries run in the order agent.yaml lists them. Nothing here is sorted or
    # reordered: an entry reading a value a later entry assigns was refused at
    # compile time, so by here the order is known good.
`)
	for _, entry := range agent.Prefetch {
		b.WriteString("\n")
		switch {
		case entry.Clock != "":
			writePrefetchClock(&b, agent, entry)
		case entry.Source != "":
			writePrefetchSource(&b, agent, entry)
		default:
			writePrefetchTool(&b, agent, entry, stateExpr, request(entry))
		}
	}
	block.Source = b.String()
	return block, true
}

// writePrefetchClock emits the clock branch. No skip arm: a clock always reads,
// so there is no empty input that could make this entry do nothing, and no
// try/except either, because reading a validated zone raises nothing.
func writePrefetchClock(b *strings.Builder, agent *ir.Agent, entry ir.Prefetch) {
	fmt.Fprintf(b, "    # %s: clock -> %s\n", entry.Name, prefetchAssignedNames(entry))
	for _, pair := range entry.Assign {
		fmt.Fprintf(b, "    state.%s = datetime.now(_PREFETCH_TZ).date().isoformat()\n", pair.Key)
		writeUnconfirmed(b, agent, entry, pair.Key)
	}
	// An f-string, not a %s placeholder and not .format(), because this block is
	// rendered into both drivers and they log through different libraries: LiveKit
	// gets stdlib logging, which interpolates %s, and Pipecat gets loguru, which
	// interpolates {}. Passing either style to the other prints the placeholder
	// literally, which is exactly what a real Pipecat smoke run showed. A string
	// already formatted by Python is the one form both accept.
	fmt.Fprintf(b, "    logger.info(f\"prefetch %s: resolved %s={state.%s}\")\n",
		entry.Name, entry.Assign[0].Key, entry.Assign[0].Key)
}

// writePrefetchSource emits the call-fact branch: read the named fact out of the
// call context, skip with a log line when the route supplied none.
func writePrefetchSource(b *strings.Builder, agent *ir.Agent, entry ir.Prefetch) {
	fmt.Fprintf(b, "    # %s: source %s -> %s\n", entry.Name, entry.Source, prefetchAssignedNames(entry))
	fmt.Fprintf(b, "    _value = (call_context or {}).get(%s) or \"\"\n", pyQuote(string(entry.Source)))
	b.WriteString("    if not _value:\n")
	fmt.Fprintf(b, "        logger.info(\"prefetch %s: skipped, the call carries no %s\")\n", entry.Name, entry.Source)
	b.WriteString("    else:\n")
	for _, pair := range entry.Assign {
		fmt.Fprintf(b, "        state.%s = _prefetch_bounded(%s, _value)\n", pair.Key, pyQuote(pair.Key))
		writeUnconfirmedIndented(b, agent, entry, pair.Key, "        ")
	}
	fmt.Fprintf(b, "        logger.info(\"prefetch %s: resolved %s%s\")\n",
		entry.Name, prefetchAssignedNames(entry), prefetchConfirmSuffix(agent, entry))
}

// writePrefetchTool emits the lookup branch: skip when any input is empty, run
// inside the budget, and swallow both failure modes. Neither except arm
// re-raises: a pre-fetch that fails is a call that greets on time with the
// values at their defaults, which is exactly what a route supplying no caller ID
// already does.
func writePrefetchTool(b *strings.Builder, agent *ir.Agent, entry ir.Prefetch, stateExpr string, request PrefetchRequest) {
	fmt.Fprintf(b, "    # %s: %s(%s) -> %s\n", entry.Name, entry.Tool,
		strings.Join(prefetchArgSummary(entry), ", "), prefetchAssignedNames(entry))
	// An entry with no inputs cannot skip, so it gets no skip arm and no `else`:
	// the body sits at the entry's own indentation. An entry with inputs is
	// skipped when any of them is empty, which is the whole degrade path.
	indent, body := "    ", "        "
	if len(entry.Inputs) > 0 {
		guards := make([]string, 0, len(entry.Inputs))
		for _, input := range entry.Inputs {
			guards = append(guards, "not state."+input)
		}
		fmt.Fprintf(b, "    if %s:\n", strings.Join(guards, " or "))
		fmt.Fprintf(b, "        logger.info(\"prefetch %s: skipped, %s is empty\")\n",
			entry.Name, strings.Join(entry.Inputs, " or "))
		b.WriteString("    else:\n")
		indent, body = "        ", "            "
	}
	fmt.Fprintf(b, "%stry:\n", indent)
	fmt.Fprintf(b, "%sasync with asyncio.timeout(_PREFETCH_BUDGET_S):\n", body)
	if request.Local {
		fmt.Fprintf(b, "%s    result = tools.%s.%s(%s)\n", body, request.Name, request.Name, request.CallKwargs)
		fmt.Fprintf(b, "%s    if inspect.isawaitable(result):\n", body)
		fmt.Fprintf(b, "%s        result = await result\n", body)
	} else {
		fmt.Fprintf(b, "%s    async with httpx.AsyncClient() as client:\n", body)
		auth := ""
		if request.AuthExpr != "" {
			auth = "headers=" + request.AuthExpr + ", "
		}
		fmt.Fprintf(b, "%s        response = await client.post(%s, %sjson=%s, timeout=_PREFETCH_BUDGET_S)\n",
			body, request.URLExpr, auth, request.BodyExpr)
		fmt.Fprintf(b, "%s        response.raise_for_status()\n", body)
		fmt.Fprintf(b, "%s        result = response.json()\n", body)
	}
	for _, pair := range entry.Assign {
		field, _ := strings.CutPrefix(pair.Value.(string), "result.")
		fmt.Fprintf(b, "%sstate.%s = _prefetch_bounded(%s, (result or {}).get(%s))\n",
			body, pair.Key, pyQuote(pair.Key), pyQuote(field))
		writeUnconfirmedIndented(b, agent, entry, pair.Key, body)
	}
	fmt.Fprintf(b, "%slogger.info(\"prefetch %s: resolved %s%s\")\n",
		body, entry.Name, prefetchAssignedNames(entry), prefetchConfirmSuffix(agent, entry))
	fmt.Fprintf(b, "%sexcept TimeoutError:\n", indent)
	fmt.Fprintf(b, "%slogger.warning(\n", body)
	fmt.Fprintf(b, "%s    f\"prefetch %s: gave up after {_PREFETCH_BUDGET_S}s; %s keeps its default\"\n",
		body, entry.Name, prefetchAssignedNames(entry))
	fmt.Fprintf(b, "%s)\n", body)
	fmt.Fprintf(b, "%sexcept Exception:\n", indent)
	fmt.Fprintf(b, "%slogger.exception(\"prefetch %s: failed; %s keeps its default\")\n",
		body, entry.Name, prefetchAssignedNames(entry))
	_ = stateExpr
}

// writeUnconfirmed marks one value as awaiting the caller's agreement.
func writeUnconfirmed(b *strings.Builder, agent *ir.Agent, entry ir.Prefetch, name string) {
	writeUnconfirmedIndented(b, agent, entry, name, "    ")
}

func writeUnconfirmedIndented(b *strings.Builder, agent *ir.Agent, entry ir.Prefetch, name, indent string) {
	if agent.Variables[name].Confirm == "" {
		return
	}
	fmt.Fprintf(b, "%sstate._unconfirmed.add(%s)\n", indent, pyQuote(name))
	_ = entry
}

// prefetchConfirms reports whether any value this entry assigns needs the
// caller's agreement, which is what decides whether the block emits the set.
func prefetchConfirms(agent *ir.Agent, entry ir.Prefetch) bool {
	for _, pair := range entry.Assign {
		if agent.Variables[pair.Key].Confirm != "" {
			return true
		}
	}
	return false
}

// prefetchConfirmSuffix is the log line's tail. A value the caller still has to
// agree to is a different outcome from one that is settled, and the log says so:
// reading a trace back is how this feature is verified.
func prefetchConfirmSuffix(agent *ir.Agent, entry ir.Prefetch) string {
	if prefetchConfirms(agent, entry) {
		return ", awaiting confirmation"
	}
	return ""
}

// prefetchAssignedNames lists what an entry lands, for a comment and a log line.
func prefetchAssignedNames(entry ir.Prefetch) string {
	names := make([]string, 0, len(entry.Assign))
	for _, pair := range entry.Assign {
		names = append(names, pair.Key)
	}
	return strings.Join(names, ", ")
}

// prefetchArgSummary is the entry's arguments as the author wrote them, for the
// comment above the call. The author's own text, so a reader can match the
// emitted line to the line in agent.yaml.
func prefetchArgSummary(entry ir.Prefetch) []string {
	out := make([]string, 0, len(entry.Args))
	for _, pair := range entry.Args {
		out = append(out, fmt.Sprintf("%s=%v", pair.Key, pair.Value))
	}
	return out
}

// PrefetchRunbook is the emitted README section, written once so both targets'
// runbooks say the same thing.
//
// The runbook is the file somebody reads at three in the morning, and the
// questions it has to answer are the ones the code cannot: which zone the clock
// was read in, how long the greeting can be delayed, what happens on a route that
// carries no caller ID, and which day a call that crosses midnight keeps using.
// That last one is the trap: nothing about the emitted code hints that the answer
// is "the day it started on".
func PrefetchRunbook(agent *ir.Agent) (string, bool) {
	if len(agent.Prefetch) == 0 {
		return "", false
	}
	var b strings.Builder
	b.WriteString("\n## Facts resolved before the greeting\n\n")
	b.WriteString("This agent resolves some values once per call, before it speaks, so the model\n" +
		"never spends a turn discovering them. Each entry below runs in the order\n" +
		"`agent.yaml` lists it.\n\n")
	b.WriteString("| Entry | Reads | Lands in |\n|---|---|---|\n")
	for _, entry := range agent.Prefetch {
		reads := ""
		switch {
		case entry.Clock != "":
			reads = "the clock, in `" + agent.Timezone + "`"
		case entry.Source != "":
			reads = "the call's own `" + string(entry.Source) + "`"
		default:
			reads = "`" + entry.Tool + "`, a read-only lookup"
		}
		fmt.Fprintf(&b, "| `%s` | %s | `%s` |\n", entry.Name, reads, prefetchAssignedNames(entry))
	}
	b.WriteString("\n**The budget.** The whole block has " +
		strconv.FormatFloat(PrefetchBudget, 'f', 1, 64) +
		" seconds, which you will find in the\ncode as `_PREFETCH_BUDGET_S`. " +
		"Past that it gives up, the\nvalues keep their declared defaults, and the call greets on time. " +
		"Nothing here can\nfail a call: a lookup that times out or raises is logged and stepped over.\n")
	b.WriteString("\n**An entry can do nothing, and that is normal.** An entry whose inputs are empty\n" +
		"is skipped. A call that carries no caller ID skips every entry that reads one,\n" +
		"and every entry downstream of those, so the agent behaves exactly as it would\n" +
		"have without this block at all. Compiling for a target whose route supplies no\n" +
		"call facts prints a warning naming each entry it will skip there.\n")
	if hasPrefetchClock(agent) {
		b.WriteString("\n**The clock is read once, at session start, in `" + agent.Timezone + "`.** " +
			"Not the\ncontainer's clock, which is UTC and would name the wrong day for anybody who is\n" +
			"not on it.\n\n**A call that crosses midnight keeps the day it started on.** " +
			"The value is read\nonce and never refreshed, so a call beginning at 23:55 still says that day at\n" +
			"00:10. This is deliberate: a value that changed underneath a conversation would\n" +
			"be worse, because the caller and the agent would stop agreeing about what\n" +
			"\"tomorrow\" means halfway through. If a call really can outlast midnight and the\n" +
			"date has to follow, read it in a tool instead of pre-fetching it.\n")
	}
	if PrefetchUnconfirmed(agent) {
		b.WriteString("\n**A pre-fetched value can need confirming.** ")
		names := make([]string, 0, len(agent.Variables))
		for _, name := range sortedKeys(agent.Variables) {
			if agent.Variables[name].Confirm != "" {
				names = append(names, "`"+name+"` (confirmed by `"+agent.Variables[name].Confirm+"`)")
			}
		}
		b.WriteString(strings.Join(names, ", ") + " arrive\nfilled but not yet agreed to. Until the naming step has heard the caller agree,\n" +
			"such a value satisfies no `requires:` guard and appears in no prompt except that\n" +
			"step's own. So the agent reads the value back and asks for a yes rather than\n" +
			"acting on it, which is what stops somebody ringing from a friend's phone being\n" +
			"treated as the account holder.\n")
	}
	b.WriteString("\n**What you see in the log.** One line per entry, naming the entry and the values:\n\n```text\n")
	b.WriteString("prefetch " + agent.Prefetch[0].Name + ": resolved " + prefetchAssignedNames(agent.Prefetch[0]) + "\n")
	b.WriteString("prefetch " + agent.Prefetch[len(agent.Prefetch)-1].Name + ": skipped, ...\n")
	b.WriteString("```\n\nA value is never written to the log, only its name, which matters when it is\n" +
		"something like a phone number.\n")
	return b.String(), true
}

// hasPrefetchClock reports whether any entry reads the clock, which is what makes
// the timezone and the midnight answer worth a runbook section.
func hasPrefetchClock(agent *ir.Agent) bool {
	for _, entry := range agent.Prefetch {
		if entry.Clock != "" {
			return true
		}
	}
	return false
}

// prefetchRequestFor builds one entry's request from the same helpers the
// mid-call tool path uses: urlExpr for the URL, injectExpr for every value,
// requestBody and callKwargs for the shape, loweredAuth for the headers.
//
// The entry's own `args:` are lowered exactly as `inject:` is, which is the
// promise the contract makes ("same value grammar as inject:, written as a
// list"), and the tool's own `inject:` values are merged in on top, because a
// pre-fetched call is still that tool's call and its hidden values still belong
// in it.
//
// Both drivers call this. That is the answer to "reuse the request building
// rather than writing a second one": the parts that drift, URL assembly and auth
// and injected values, have one owner, and it is this function.
func prefetchRequestFor(agent *ir.Agent, entry ir.Prefetch) PrefetchRequest {
	tool := agent.Tools[entry.Tool]
	values := make([]injectedValue, 0, len(entry.Args)+len(tool.Inject))
	for _, pair := range entry.Args {
		values = append(values, injectedValue{Key: pair.Key, Expr: injectExpr(pair.Value, prefetchStateExpr)})
	}
	injected, _ := loweredInject(tool, agent.Variables, prefetchStateExpr)
	values = append(values, injected...)
	request := PrefetchRequest{Name: entry.Tool, Local: tool.Execution == ir.ToolLocal}
	if request.Local {
		request.CallKwargs = callKwargs(nil, values)
		return request
	}
	request.URLExpr = urlExpr(tool, prefetchStateExpr)
	request.BodyExpr = requestBody(nil, values)
	if auth := loweredAuth(tool.Auth); auth != nil {
		request.AuthExpr = auth.Expr
	}
	return request
}

// PrefetchNeedsSeed reports whether any entry reads a call fact, which is what
// makes the local seed worth passing into the container.
//
// Read off the agent rather than off a driver's own flag, because both drivers set
// their DevOptionalEnv list before they lower the block: reading the flag there
// silently answered "no" every time, and the seed never reached the container.
func PrefetchNeedsSeed(agent *ir.Agent) bool {
	for _, entry := range agent.Prefetch {
		if entry.Source != "" {
			return true
		}
	}
	return false
}

// prefetchNeedsHTTPX reports whether any pre-fetched tool is a webhook, which is
// what pulls the httpx import into a package whose mid-call tools are all local.
func prefetchNeedsHTTPX(agent *ir.Agent) bool {
	for _, entry := range agent.Prefetch {
		if entry.Tool != "" && agent.Tools[entry.Tool].Execution == ir.ToolWebhook {
			return true
		}
	}
	return false
}

// prefetchStateExpr is how the emitted block reaches the call state. It differs
// from each driver's mid-call expression on purpose: a pre-fetch runs before any
// RunContext or FunctionCallParams exists, so it holds the state object directly
// and every value expression it builds has to say `state` rather than
// `ctx.userdata` or `state` off a params object.
const prefetchStateExpr = "state"

// PrefetchUnconfirmed reports whether a package has any value awaiting the
// caller's agreement, which is what decides whether the guard consults the set.
func PrefetchUnconfirmed(agent *ir.Agent) bool {
	for _, name := range sortedKeys(agent.Variables) {
		if agent.Variables[name].Confirm != "" {
			return true
		}
	}
	return false
}
